require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'Drybar' do
  rn_maps_path = '../node_modules/react-native-maps'
    pod 'react-native-google-maps', :path => rn_maps_path
    pod 'GoogleMaps'
    pod 'Google-Maps-iOS-Utils'
  config = use_native_modules!

  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-LocationAlways', :path => "#{permissions_path}/LocationAlways"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse"
  pod 'react-native-appboy-sdk', :path => '../node_modules/react-native-appboy-sdk'

  pod 'mParticle-Apple-SDK', '~> 8'

  use_react_native!(:path => config["reactNativePath"])



  pod 'OktaSdkBridgeReactNative', :path => '../node_modules/@okta/okta-react-native'
  pod 'react-native-add-calendar-event', :path => '../node_modules/react-native-add-calendar-event'

  target 'DrybarTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  #use_flipper!
  #post_install do |installer|
  #flipper_post_install(installer)
  #end
end

target 'Drybar-tvOS' do
  # Pods for Drybar-tvOS

  target 'Drybar-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
